System.config({
  baseURL: "/",
  defaultJSExtensions: true,
  transpiler: "babel",
  babelOptions: {
    "optional": [
      "runtime",
      "optimisation.modules.system"
    ]
  },
  paths: {
    "github:*": "jspm_packages/github/*",
    "npm:*": "jspm_packages/npm/*"
  },
  bundles: {
    "build/build.js": [
      "app.js",
      "lib.js",
      "npm:babel-runtime@5.8.20/core-js/promise",
      "npm:babel-runtime@5.8.20/helpers/sliced-to-array",
      "npm:babel-runtime@5.8.20/core-js/get-iterator",
      "npm:babel-runtime@5.8.20/regenerator",
      "npm:babel-runtime@5.8.20/core-js/map",
      "npm:babel-runtime@5.8.20/core-js/object/keys",
      "npm:core-js@1.1.4/library/fn/promise",
      "npm:babel-runtime@5.8.20/core-js/is-iterable",
      "npm:core-js@1.1.4/library/fn/get-iterator",
      "npm:babel-runtime@5.8.20/regenerator/index",
      "npm:core-js@1.1.4/library/fn/object/keys",
      "npm:core-js@1.1.4/library/fn/map",
      "npm:core-js@1.1.4/library/modules/es6.object.to-string",
      "npm:core-js@1.1.4/library/modules/es6.string.iterator",
      "npm:core-js@1.1.4/library/modules/web.dom.iterable",
      "npm:core-js@1.1.4/library/modules/$.core",
      "npm:core-js@1.1.4/library/modules/es6.promise",
      "npm:core-js@1.1.4/library/modules/core.get-iterator",
      "npm:babel-runtime@5.8.20/regenerator/runtime",
      "npm:core-js@1.1.4/library/fn/is-iterable",
      "npm:core-js@1.1.4/library/modules/es6.object.keys",
      "npm:core-js@1.1.4/library/modules/es7.map.to-json",
      "npm:core-js@1.1.4/library/modules/es6.map",
      "npm:core-js@1.1.4/library/modules/$.string-at",
      "npm:core-js@1.1.4/library/modules/$.iterators",
      "npm:core-js@1.1.4/library/modules/es6.array.iterator",
      "npm:core-js@1.1.4/library/modules/$.global",
      "github:jspm/nodelibs-process@0.1.1",
      "npm:core-js@1.1.4/library/modules/$.iter-define",
      "npm:core-js@1.1.4/library/modules/$",
      "npm:core-js@1.1.4/library/modules/$.library",
      "npm:core-js@1.1.4/library/modules/$.ctx",
      "npm:core-js@1.1.4/library/modules/$.classof",
      "npm:core-js@1.1.4/library/modules/$.is-object",
      "npm:core-js@1.1.4/library/modules/$.def",
      "npm:core-js@1.1.4/library/modules/$.for-of",
      "npm:core-js@1.1.4/library/modules/$.an-object",
      "npm:core-js@1.1.4/library/modules/$.strict-new",
      "npm:core-js@1.1.4/library/modules/$.a-function",
      "npm:core-js@1.1.4/library/modules/$.same",
      "npm:core-js@1.1.4/library/modules/$.set-proto",
      "npm:core-js@1.1.4/library/modules/$.species",
      "npm:core-js@1.1.4/library/modules/$.wks",
      "npm:core-js@1.1.4/library/modules/$.tag",
      "npm:core-js@1.1.4/library/modules/$.uid",
      "npm:core-js@1.1.4/library/modules/$.support-desc",
      "npm:core-js@1.1.4/library/modules/$.iter-detect",
      "npm:core-js@1.1.4/library/modules/$.microtask",
      "npm:core-js@1.1.4/library/modules/$.mix",
      "npm:core-js@1.1.4/library/modules/core.get-iterator-method",
      "npm:babel-runtime@5.8.20/core-js/symbol/iterator",
      "npm:babel-runtime@5.8.20/core-js/symbol",
      "npm:babel-runtime@5.8.20/core-js/object/create",
      "npm:core-js@1.1.4/library/modules/$.collection-to-json",
      "npm:core-js@1.1.4/library/modules/$.to-object",
      "npm:core-js@1.1.4/library/modules/core.is-iterable",
      "npm:core-js@1.1.4/library/modules/$.object-sap",
      "npm:core-js@1.1.4/library/modules/$.collection-strong",
      "npm:core-js@1.1.4/library/modules/$.collection",
      "npm:core-js@1.1.4/library/modules/$.iter-step",
      "npm:core-js@1.1.4/library/modules/$.defined",
      "npm:core-js@1.1.4/library/modules/$.unscope",
      "npm:core-js@1.1.4/library/modules/$.to-integer",
      "github:jspm/nodelibs-process@0.1.1/index",
      "npm:core-js@1.1.4/library/modules/$.redef",
      "npm:core-js@1.1.4/library/modules/$.hide",
      "npm:core-js@1.1.4/library/modules/$.to-iobject",
      "npm:core-js@1.1.4/library/modules/$.iter-create",
      "npm:core-js@1.1.4/library/modules/$.cof",
      "npm:core-js@1.1.4/library/modules/$.iter-call",
      "npm:core-js@1.1.4/library/modules/$.has",
      "npm:core-js@1.1.4/library/modules/$.shared",
      "npm:core-js@1.1.4/library/modules/$.to-length",
      "npm:core-js@1.1.4/library/modules/$.fails",
      "npm:core-js@1.1.4/library/modules/$.is-array-iter",
      "npm:core-js@1.1.4/library/modules/$.task",
      "npm:core-js@1.1.4/library/fn/symbol/iterator",
      "npm:core-js@1.1.4/library/fn/object/create",
      "npm:core-js@1.1.4/library/fn/symbol",
      "npm:process@0.10.1",
      "npm:core-js@1.1.4/library/modules/$.iobject",
      "npm:core-js@1.1.4/library/modules/$.property-desc",
      "npm:core-js@1.1.4/library/modules/$.invoke",
      "npm:core-js@1.1.4/library/fn/symbol/index",
      "npm:core-js@1.1.4/library/modules/$.html",
      "npm:core-js@1.1.4/library/modules/$.dom-create",
      "npm:process@0.10.1/browser",
      "npm:core-js@1.1.4/library/modules/es6.symbol",
      "npm:core-js@1.1.4/library/modules/$.get-names",
      "npm:core-js@1.1.4/library/modules/$.keyof",
      "npm:core-js@1.1.4/library/modules/$.enum-keys"
    ]
  },

  map: {
    "babel": "npm:babel-core@5.8.23",
    "babel-runtime": "npm:babel-runtime@5.8.20",
    "core-js": "npm:core-js@1.1.4",
    "github:jspm/nodelibs-process@0.1.1": {
      "process": "npm:process@0.10.1"
    },
    "npm:babel-runtime@5.8.20": {
      "process": "github:jspm/nodelibs-process@0.1.1"
    },
    "npm:core-js@1.1.4": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "process": "github:jspm/nodelibs-process@0.1.1",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    }
  }
});
